services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hcrm-app-prod
    restart: always
    env_file: .env.prod
    environment:
      NODE_ENV: production
      PORT: "5001"
    ports:
      - "3000:5001"

networks:
  default:
    driver: bridge
